#ifndef ZERO_COST_SERIALIZATION_UNSAFE_BUFFER_USAGE_BEGIN
#define ZERO_COST_SERIALIZATION_UNSAFE_BUFFER_USAGE_BEGIN
#endif

#ifndef ZERO_COST_SERIALIZATION_UNSAFE_BUFFER_USAGE_END
#define ZERO_COST_SERIALIZATION_UNSAFE_BUFFER_USAGE_END
#endif

#ifndef ZERO_COST_SERIALIZATION_THIS_USED_IN_MEMBER_INIT
#define ZERO_COST_SERIALIZATION_THIS_USED_IN_MEMBER_INIT _Pragma("warning (suppress: 4355)")
#endif

#ifndef ZERO_COST_SERIALIZATION_MISSING_BRACES
#define ZERO_COST_SERIALIZATION_MISSING_BRACES _Pragma("warning (suppress: 5246)")
#endif
